from __future__ import annotations

from typing import Any


LEGACY_TO_CANONICAL_FEATURE_KEY = {
    "beginner_fit_score": "beginner_fit",
    "stability_score": "stability",
    "all_round_score": "all_round",
}

CANONICAL_TO_DOMAIN_FEATURE_KEY = {
    "hitting_sound": "sound",
    "beginner_fit": "beginner_fit_score",
    "stability": "stability_score",
    "all_round": "all_round_score",
    "attacking_fit": "attacking_fit_score",
    "control_fit": "control_fit_score",
}

CANONICAL_MATRIX_FEATURE_KEYS = (
    "attack",
    "comfort",
    "control",
    "durability",
    "elasticity",
    "hitting_sound",
    "string_movement",
    "tension_retention",
    "value_for_money",
    "beginner_fit",
    "stability",
    "all_round",
    "attacking_fit",
    "control_fit",
)

DOMAIN_ASPECT_FEATURE_KEYS = {
    "repulsion",
    "attack",
    "comfort",
    "control",
    "durability",
    "elasticity",
    "sound",
    "string_movement",
    "tension_retention",
    "value_for_money",
    "beginner_fit_score",
    "stability_score",
    "all_round_score",
    "attacking_fit_score",
    "control_fit_score",
}

RECOMMENDATION_FEATURE_DEFINITIONS: list[dict[str, Any]] = [
    {
        "feature_key": "repulsion",
        "feature_label": "Repulsion",
        "feature_group": "catalog_aspect",
        "data_type": "score",
        "min_value": 0,
        "max_value": 1,
        "description": "Power and rebound response.",
    },
    {
        "feature_key": "attack",
        "feature_label": "Attack",
        "feature_group": "catalog_aspect",
        "data_type": "score",
        "min_value": 0,
        "max_value": 1,
        "description": "Explosive offensive response.",
    },
    {
        "feature_key": "comfort",
        "feature_label": "Comfort",
        "feature_group": "catalog_aspect",
        "data_type": "score",
        "min_value": 0,
        "max_value": 1,
        "description": "Overall comfort and feel on impact.",
    },
    {
        "feature_key": "control",
        "feature_label": "Control",
        "feature_group": "catalog_aspect",
        "data_type": "score",
        "min_value": 0,
        "max_value": 1,
        "description": "Control-oriented response.",
    },
    {
        "feature_key": "durability",
        "feature_label": "Durability",
        "feature_group": "catalog_aspect",
        "data_type": "score",
        "min_value": 0,
        "max_value": 1,
        "description": "Resistance to snapping and wear.",
    },
    {
        "feature_key": "elasticity",
        "feature_label": "Elasticity",
        "feature_group": "catalog_aspect",
        "data_type": "score",
        "min_value": 0,
        "max_value": 1,
        "description": "Elastic rebound feel.",
    },
    {
        "feature_key": "sound",
        "feature_label": "Sound",
        "feature_group": "catalog_aspect",
        "data_type": "score",
        "min_value": 0,
        "max_value": 1,
        "description": "User-facing hitting sound response.",
    },
    {
        "feature_key": "hitting_sound",
        "feature_label": "Hitting Sound",
        "feature_group": "catalog_aspect",
        "data_type": "score",
        "min_value": 0,
        "max_value": 1,
        "description": "Crisp sound response.",
    },
    {
        "feature_key": "string_movement",
        "feature_label": "String Movement",
        "feature_group": "catalog_aspect",
        "data_type": "score",
        "min_value": 0,
        "max_value": 1,
        "description": "String bed movement behaviour.",
    },
    {
        "feature_key": "tension_retention",
        "feature_label": "Tension Retention",
        "feature_group": "catalog_aspect",
        "data_type": "score",
        "min_value": 0,
        "max_value": 1,
        "description": "Ability to hold tension over time.",
    },
    {
        "feature_key": "value_for_money",
        "feature_label": "Value for Money",
        "feature_group": "catalog_aspect",
        "data_type": "score",
        "min_value": 0,
        "max_value": 1,
        "description": "Perceived value for price paid.",
    },
    {
        "feature_key": "beginner_fit",
        "feature_label": "Beginner Fit",
        "feature_group": "derived_aspect",
        "data_type": "score",
        "min_value": 0,
        "max_value": 1,
        "description": "Derived beginner-friendliness score.",
    },
    {
        "feature_key": "stability",
        "feature_label": "Stability",
        "feature_group": "derived_aspect",
        "data_type": "score",
        "min_value": 0,
        "max_value": 1,
        "description": "Derived stability score.",
    },
    {
        "feature_key": "all_round",
        "feature_label": "All Round",
        "feature_group": "derived_aspect",
        "data_type": "score",
        "min_value": 0,
        "max_value": 1,
        "description": "Derived all-round playability score.",
    },
    {
        "feature_key": "attacking_fit",
        "feature_label": "Attacking Fit",
        "feature_group": "derived_aspect",
        "data_type": "score",
        "min_value": 0,
        "max_value": 1,
        "description": "Derived fit score for attacking players.",
    },
    {
        "feature_key": "control_fit",
        "feature_label": "Control Fit",
        "feature_group": "derived_aspect",
        "data_type": "score",
        "min_value": 0,
        "max_value": 1,
        "description": "Derived fit score for control-oriented players.",
    },
    {
        "feature_key": "gauge_mm",
        "feature_label": "Gauge (mm)",
        "feature_group": "catalog_structured",
        "data_type": "number",
        "min_value": 0.5,
        "max_value": 0.8,
        "description": "Nominal string gauge.",
    },
    {
        "feature_key": "price_rm",
        "feature_label": "Price (RM)",
        "feature_group": "catalog_structured",
        "data_type": "number",
        "min_value": 0,
        "max_value": 999,
        "description": "Current store selling price in MYR.",
    },
    {
        "feature_key": "skill_level_weight",
        "feature_label": "Skill Level Weight",
        "feature_group": "user_preference",
        "data_type": "weight",
        "min_value": 0,
        "max_value": 1,
        "description": "Weight derived from player skill level.",
    },
    {
        "feature_key": "playing_style_weight",
        "feature_label": "Playing Style Weight",
        "feature_group": "user_preference",
        "data_type": "weight",
        "min_value": 0,
        "max_value": 1,
        "description": "Weight derived from playing style.",
    },
    {
        "feature_key": "durability_preference",
        "feature_label": "Durability Preference",
        "feature_group": "user_preference",
        "data_type": "weight",
        "min_value": 0,
        "max_value": 1,
        "description": "Player durability preference.",
    },
    {
        "feature_key": "repulsion_preference",
        "feature_label": "Repulsion Preference",
        "feature_group": "user_preference",
        "data_type": "weight",
        "min_value": 0,
        "max_value": 1,
        "description": "Player repulsion preference.",
    },
    {
        "feature_key": "control_preference",
        "feature_label": "Control Preference",
        "feature_group": "user_preference",
        "data_type": "weight",
        "min_value": 0,
        "max_value": 1,
        "description": "Player control preference.",
    },
    {
        "feature_key": "sound_preference",
        "feature_label": "Sound Preference",
        "feature_group": "user_preference",
        "data_type": "weight",
        "min_value": 0,
        "max_value": 1,
        "description": "Player sound preference.",
    },
    {
        "feature_key": "comfort_preference",
        "feature_label": "Comfort Preference",
        "feature_group": "user_preference",
        "data_type": "weight",
        "min_value": 0,
        "max_value": 1,
        "description": "Player comfort preference.",
    },
]


def canonical_feature_key(feature_key: str) -> str:
    return LEGACY_TO_CANONICAL_FEATURE_KEY.get(feature_key, feature_key)


def domain_feature_key(feature_key: str) -> str:
    canonical_key = canonical_feature_key(feature_key)
    return CANONICAL_TO_DOMAIN_FEATURE_KEY.get(canonical_key, canonical_key)
